FROM maven:3.9-eclipse-temurin-21-alpine
WORKDIR /app
COPY pom.xml ./
COPY src ./src
COPY .env ./
RUN mvn clean package -DskipTests
RUN mvn -q compile
COPY . .
ENTRYPOINT ["mvn", "-q", "exec:java", "-Dexec.mainClass=CreateOrder"]
