FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine
WORKDIR /app

# Copy csproj and restore dependencies
COPY Authentication.csproj ./
RUN dotnet restore

# Copy the rest of the files
COPY . ./

# Run the application directly with dotnet run
ENTRYPOINT ["dotnet", "run", "--", "get"]
