FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore dependencies
COPY CreateOrder.csproj ./
RUN dotnet restore

# Copy the rest of the files and build
COPY . ./
RUN dotnet build -c Release -o /app/build

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/build .

# Run the application
ENTRYPOINT ["dotnet", "CreateOrder.dll", "create"]
