FROM rust:1.85

WORKDIR /usr/src/app

# Copy the Cargo.toml file
COPY Cargo.toml ./

# Copy the source code
COPY src ./src
COPY .env ./.env

# Build the application
RUN cargo build --bin cancel

# Run the application
CMD ["cargo", "run", "--bin", "cancel"]
