FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y \
    coreutils \
    curl \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
COPY create-order.sh /usr/local/bin/create-order.sh
COPY .env /usr/local/bin/.env
RUN chmod +x /usr/local/bin/create-order.sh
ENTRYPOINT ["/usr/local/bin/create-order.sh"]
