FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y \
    coreutils \
    curl \
    wget \
    && wget https://github.com/vi/websocat/releases/download/v1.13.0/websocat.x86_64-unknown-linux-musl -O /usr/local/bin/websocat \
    && chmod +x /usr/local/bin/websocat \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
WORKDIR /usr/local/bin
COPY create-order.sh .
COPY .env .
RUN chmod +x create-order.sh
ENTRYPOINT ["./create-order.sh"]
